export const PATH_UNCONTROLED_FORM = 'uncontrolled-form';
export const PATH_REACT_HOOK_FORM = 'react-hook-form';

export const initialCountries = [
  'Russia',
  'USA',
  'China',
  'India',
  'Brazil',
  'Canada',
  'France',
  'Germany',
  'United Kingdom',
  'Japan',
  'Australia',
  'South Korea',
  'Mexico',
  'Spain',
  'Italy',
  'Argentina',
  'South Africa',
  'Nigeria',
  'Egypt',
  'Saudi Arabia',
  'Turkey',
  'Indonesia',
  'Thailand',
  'Vietnam',
  'Malaysia',
  'Pakistan',
  'Iran',
  'Iraq',
  'Israel',
  'Jordan',
  'Lebanon',
  'United Arab Emirates',
  'Qatar',
  'Kuwait',
  'Oman',
  'Yemen',
  'United States',
  'Canada',
  'Mexico',
  'Brazil',
  'Chile',
  'Colombia',
  'Peru',
  'Ecuador',
  'Venezuela',
  'Cuba',
  'Jamaica',
];
